//
//  WorkoutSamples.swift
//  WeldEngineer
//
//  Created by Joseph DeWeese on 8/4/24.
//


import Foundation

extension Project {
    static let lastWeek = Calendar.current.date(byAdding: .day, value: -7, to: Date.now)!
    static let lastMonth = Calendar.current.date(byAdding: .month, value: -1, to: Date.now)!
    static var sampleProjects:[Project] {
        [
            Project(title: "4043 Aluminum Qualification", briefDescription: "Develop WPS", location: "Bolivar", engineer: "DDeWeese", dateAdded: Date.distantPast, projectSummary: "Lorem ipsum odor amet, consectetuer adipiscing elit. Suscipit semper consequat scelerisque nostra congue elit. Mi phasellus neque aliquet, himenaeos varius volutpat. Etiam sollicitudin imperdiet dolor ultricies faucibus non vel curae. Morbi sollicitudin non ullamcorper porttitor quam nascetur morbi. Sed fames ut a ligula eget nascetur feugiat placerat. Pharetra neque posuere hac varius hendrerit. Orci aptent primis vivamus viverra magnis.", problemDefinition: "Lorem ipsum odor amet, consectetuer adipiscing elit. Suscipit semper consequat scelerisque nostra congue elit. Mi phasellus neque aliquet, himenaeos varius volutpat. Etiam sollicitudin imperdiet dolor ultricies faucibus non vel curae. Morbi sollicitudin non ullamcorper porttitor quam nascetur morbi. Sed fames ut a ligula eget nascetur feugiat placerat. Pharetra neque posuere hac varius hendrerit. Orci aptent primis vivamus viverra magnis."),
            Project(title: "6005A Aluminum Qualification", briefDescription: "Develop WPS", location:  "Ozark", engineer: "RDeWeese", dateAdded: Date.distantPast, projectSummary: "Lorem ipsum odor amet, consectetuer adipiscing elit. Suscipit semper consequat scelerisque nostra congue elit. Mi phasellus neque aliquet, himenaeos varius volutpat. Etiam sollicitudin imperdiet dolor ultricies faucibus non vel curae. Morbi sollicitudin non ullamcorper porttitor quam nascetur morbi. Sed fames ut a ligula eget nascetur feugiat placerat. Pharetra neque posuere hac varius hendrerit. Orci aptent primis vivamus viverra magnis.", problemDefinition: "Lorem ipsum odor amet, consectetuer adipiscing elit. Suscipit semper consequat scelerisque nostra congue elit. Mi phasellus neque aliquet, himenaeos varius volutpat. Etiam sollicitudin imperdiet dolor ultricies faucibus non vel curae. Morbi sollicitudin non ullamcorper porttitor quam nascetur morbi. Sed fames ut a ligula eget nascetur feugiat placerat. Pharetra neque posuere hac varius hendrerit. Orci aptent primis vivamus viverra magnis."),
            Project(title: "5052 Aluminum Qualification", briefDescription: "Develop WPS", location: "White River Marine Group", engineer: "JDeWeese", dateAdded: Date.distantPast, projectSummary: "Lorem ipsum odor amet, consectetuer adipiscing elit. Suscipit semper consequat scelerisque nostra congue elit. Mi phasellus neque aliquet, himenaeos varius volutpat. Etiam sollicitudin imperdiet dolor ultricies faucibus non vel curae. Morbi sollicitudin non ullamcorper porttitor quam nascetur morbi. Sed fames ut a ligula eget nascetur feugiat placerat. Pharetra neque posuere hac varius hendrerit. Orci aptent primis vivamus viverra magnis.", problemDefinition: "Lorem ipsum odor amet, consectetuer adipiscing elit. Suscipit semper consequat scelerisque nostra congue elit. Mi phasellus neque aliquet, himenaeos varius volutpat. Etiam sollicitudin imperdiet dolor ultricies faucibus non vel curae. Morbi sollicitudin non ullamcorper porttitor quam nascetur morbi. Sed fames ut a ligula eget nascetur feugiat placerat. Pharetra neque posuere hac varius hendrerit. Orci aptent primis vivamus viverra magnis."),
            Project(title: "5083 Aluminum Qualification", briefDescription: "Develop WPS", location:  "Base Camp", engineer: "CCooper", dateAdded: Date.distantPast, projectSummary: "Lorem ipsum odor amet, consectetuer adipiscing elit. Suscipit semper consequat scelerisque nostra congue elit. Mi phasellus neque aliquet, himenaeos varius volutpat. Etiam sollicitudin imperdiet dolor ultricies faucibus non vel curae. Morbi sollicitudin non ullamcorper porttitor quam nascetur morbi. Sed fames ut a ligula eget nascetur feugiat placerat. Pharetra neque posuere hac varius hendrerit. Orci aptent primis vivamus viverra magnis.", problemDefinition: "Lorem ipsum odor amet, consectetuer adipiscing elit. Suscipit semper consequat scelerisque nostra congue elit. Mi phasellus neque aliquet, himenaeos varius volutpat. Etiam sollicitudin imperdiet dolor ultricies faucibus non vel curae. Morbi sollicitudin non ullamcorper porttitor quam nascetur morbi. Sed fames ut a ligula eget nascetur feugiat placerat. Pharetra neque posuere hac varius hendrerit. Orci aptent primis vivamus viverra magnis."),
            Project(title: "6005A Aluminum Qualification", briefDescription: "Develop WPS", location: "Flippin", engineer: "JEmmerson", dateAdded: Date.distantPast, projectSummary: "Lorem ipsum odor amet, consectetuer adipiscing elit. Suscipit semper consequat scelerisque nostra congue elit. Mi phasellus neque aliquet, himenaeos varius volutpat. Etiam sollicitudin imperdiet dolor ultricies faucibus non vel curae. Morbi sollicitudin non ullamcorper porttitor quam nascetur morbi. Sed fames ut a ligula eget nascetur feugiat placerat. Pharetra neque posuere hac varius hendrerit. Orci aptent primis vivamus viverra magnis.", problemDefinition: "Lorem ipsum odor amet, consectetuer adipiscing elit. Suscipit semper consequat scelerisque nostra congue elit. Mi phasellus neque aliquet, himenaeos varius volutpat. Etiam sollicitudin imperdiet dolor ultricies faucibus non vel curae. Morbi sollicitudin non ullamcorper porttitor quam nascetur morbi. Sed fames ut a ligula eget nascetur feugiat placerat. Pharetra neque posuere hac varius hendrerit. Orci aptent primis vivamus viverra magnis."),
            Project(title: "5086 Aluminum Qualification", briefDescription: "Develop WPS", location: "Lebanon", engineer: "MDeWeese", dateAdded: Date.distantPast, projectSummary: "Lorem ipsum odor amet, consectetuer adipiscing elit. Suscipit semper consequat scelerisque nostra congue elit. Mi phasellus neque aliquet, himenaeos varius volutpat. Etiam sollicitudin imperdiet dolor ultricies faucibus non vel curae. Morbi sollicitudin non ullamcorper porttitor quam nascetur morbi. Sed fames ut a ligula eget nascetur feugiat placerat. Pharetra neque posuere hac varius hendrerit. Orci aptent primis vivamus viverra magnis.", problemDefinition: "Lorem ipsum odor amet, consectetuer adipiscing elit. Suscipit semper consequat scelerisque nostra congue elit. Mi phasellus neque aliquet, himenaeos varius volutpat. Etiam sollicitudin imperdiet dolor ultricies faucibus non vel curae. Morbi sollicitudin non ullamcorper porttitor quam nascetur morbi. Sed fames ut a ligula eget nascetur feugiat placerat. Pharetra neque posuere hac varius hendrerit. Orci aptent primis vivamus viverra magnis."),
        ]
    }
}
